//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingList
    {
        public int Id { get; set; }
        public string CardNo { get; set; }
        public long Item { get; set; }
        public int ShoppingListId { get; set; }
    }
}
