//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbdcInventory
    {
        public long InventoryId { get; set; }
        public long ProfileId { get; set; }
        public long NzpnaNo { get; set; }
        public Nullable<decimal> InventoryQuantity { get; set; }
        public string InventoryUnits { get; set; }
        public string InventoryApprox { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    }
}
