//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbdcCustomerProfile
    {
        public long ProfileId { get; set; }
        public string CustomerCardNo { get; set; }
        public string DisplayShopHealthMeter { get; set; }
        public string DisplayBudgetMeter { get; set; }
        public string DisplayEthicalMeter { get; set; }
        public Nullable<int> BudgetUpperLimit { get; set; }
        public Nullable<int> NumberAdultsinHouseHold { get; set; }
        public Nullable<int> NumberChildreninHouseHold { get; set; }
        public string VegetarianYN { get; set; }
        public string VeganYN { get; set; }
        public string GreenYN { get; set; }
        public string SalesImportnatYN { get; set; }
        public string BasicShoppingFrequencyWM { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
    }
}
