//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbdcProductExtention
    {
        public string NzpnaNo { get; set; }
        public string ProductDescription { get; set; }
        public string HealthRating { get; set; }
        public string EthicsRating { get; set; }
        public string Food { get; set; }
        public string Vegetarian { get; set; }
        public string Vegan { get; set; }
        public string MaleProduct { get; set; }
        public string FemaleProduct { get; set; }
        public string ChildProduct { get; set; }
        public string Departmentdescription { get; set; }
        public string SubDepartmentDescription { get; set; }
    }
}
