//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbdcBasicShopList
    {
        public int id { get; set; }
        public string customercardno { get; set; }
        public Nullable<int> frequency { get; set; }
        public Nullable<int> lastpurchaseddaysago { get; set; }
        public Nullable<decimal> avgquantitysold { get; set; }
        public string nzpnano { get; set; }
    }
}
