//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMasterArticleDepartment
    {
        public decimal DepartmentNo { get; set; }
        public decimal SubDepartmentNo { get; set; }
        public string DepartmentDescription { get; set; }
        public string SubDepartmentDescription { get; set; }
    }
}
