//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRetailTlogStoresToProcess
    {
        public int StoreMembershipNo { get; set; }
        public string StoreNameLong { get; set; }
        public string StoreType { get; set; }
        public Nullable<short> PosTypeId { get; set; }
        public string FullSapStoreInd { get; set; }
        public string ImportTlogDataInd { get; set; }
        public string IncludeInGroupPerformanceMetricsInd { get; set; }
        public Nullable<System.DateTime> RecordDateAdded { get; set; }
        public string RecordAddedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string LastUpdateUser { get; set; }
        public string Remarks { get; set; }
    }
}
